### ISSUE TITLE
No checkpoint files found in llama2-7b-chat

### ISSUE THREAD

**Issue by timfpark** [Gadersd/llama2-burn#5]
I'm attempting to try `llama2-burn` with the standard `llama2` model downloaded from Facebook and I'm seeing the following error when running `test.py`:

```
$ python llama-py/test.py ../llama2/llama2-7b-chat ../llama2/tokenizer.model
#words: 32000 BOS ID: 1 EOS ID: 2 PAD ID: -1
#words: 32000 BOS ID: 1 EOS ID: 2 PAD ID: -1
An error occurred: No checkpoint files found in ../llama2/llama2-7b-chat
```

Where `llama2` is the directory for the cloned https://github.com/facebookresearch/llama repo and which has had `download.sh` run on it.

Environment: Ubuntu 22.04 on Intel i9

**Comment by Gadersd** [comment]
Did you convert the the model files to burn's format?

**Comment by filopedraz** [comment]
Getting the same error @Gadersd

I downloaded the official weights from llama.

<img width="389" alt="image" src="https://github.com/Gadersd/llama2-burn/assets/29598954/3f7278cd-5891-47c3-b2d1-0eeb1000e50c">

```python
checkpoints = sorted(Path(model_dir).glob("*.safetensors"))
if len(checkpoints) == 0:
   raise ValueError(f"No checkpoint files found in {model_dir}")
```

But in the `test.py` script the `load_model` method searches for `*.safetensors`.

The Llama team probably compressed all the weights in a single file `consolidated.00.pth`

I created a PR (#7)

**Comment by Gadersd** [comment]
I had accidentally modified test.py to use safetensors. The issue is now resolved.
